### ISSUE TITLE
[Bug Report] picker异步数据时提示

### ISSUE THREAD

**Issue by leafhina** [youzan/vant#10576]
### 重现链接

https://youzan.github.io/vant/v4/#/zh-CN/picker

### Vant 版本

4.0.0-alpha.0

### 描述一下你遇到的问题。

```
runtime-core.esm-bundler.js:38 [Vue warn]: Invalid prop: type check failed for prop "columns". Expected Array, got Object  
  at <VanPicker ref="pickRef" columns= {0: {…}, 1: {…}} onConfirm=fn<bound onMenuSelect>  ... > 
  at <BaseTransition onAfterEnter=fn<onOpened> onAfterLeave=fn<onClosed> appear=false  ... > 
  at <Transition name="van-popup-slide-top" appear=false onAfterEnter=fn<onOpened>  ... > 
  at <VanPopup show=true onUpdate:show=fn position="top" > 
  at <Header title="标题" > 
  at <VodDetail onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:38
validateProp @ runtime-core.esm-bundler.js:3491
validateProps @ runtime-core.esm-bundler.js:3462
initProps @ runtime-core.esm-bundler.js:3161
setupComponent @ runtime-core.esm-bundler.js:7061
mountComponent @ runtime-core.esm-bundler.js:4951
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
mountChildren @ runtime-core.esm-bundler.js:4714
processFragment @ runtime-core.esm-bundler.js:4885
patch @ runtime-core.esm-bundler.js:4511
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
patchKeyedChildren @ runtime-core.esm-bundler.js:5291
patchChildren @ runtime-core.esm-bundler.js:5234
processFragment @ runtime-core.esm-bundler.js:4915
patch @ runtime-core.esm-bundler.js:4511
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
patchBlockChildren @ runtime-core.esm-bundler.js:4835
processFragment @ runtime-core.esm-bundler.js:4896
patch @ runtime-core.esm-bundler.js:4511
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueJob @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5168
triggerEffects @ reactivity.esm-bundler.js:382
trigger @ reactivity.esm-bundler.js:352
set2 @ reactivity.esm-bundler.js:509
_createVNode.onClick._cache.<computed>._cache.<computed> @ Header.vue:8
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
Show 11 more frames
runtime-core.esm-bundler.js:38 [Vue warn]: Invalid prop: type check failed for prop "options". Expected Array, got Object  
  at <VanPickerColumn value=undefined fields= {text: 'text', value: 'value', children: 'children'} options= {0: {…}, 1: {…}}  ... > 
  at <VanPicker ref="pickRef" columns= {0: {…}, 1: {…}} onConfirm=fn<bound onMenuSelect>  ... > 
  at <BaseTransition onAfterEnter=fn<onOpened> onAfterLeave=fn<onClosed> appear=false  ... > 
  at <Transition name="van-popup-slide-top" appear=false onAfterEnter=fn<onOpened>  ... > 
  at <VanPopup show=true onUpdate:show=fn position="top" > 
  at <Header title="标题" > 
  at <VodDetail onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:38
validateProp @ runtime-core.esm-bundler.js:3491
validateProps @ runtime-core.esm-bundler.js:3462
initProps @ runtime-core.esm-bundler.js:3161
setupComponent @ runtime-core.esm-bundler.js:7061
mountComponent @ runtime-core.esm-bundler.js:4951
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
mountChildren @ runtime-core.esm-bundler.js:4714
processFragment @ runtime-core.esm-bundler.js:4885
patch @ runtime-core.esm-bundler.js:4511
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
componentUpdateFn @ runtime-core.esm-bundler.js:5066
run @ reactivity.esm-bundler.js:185
setupRenderEffect @ runtime-core.esm-bundler.js:5185
mountComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
mountChildren @ runtime-core.esm-bundler.js:4714
processFragment @ runtime-core.esm-bundler.js:4885
patch @ runtime-core.esm-bundler.js:4511
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
patchKeyedChildren @ runtime-core.esm-bundler.js:5291
patchChildren @ runtime-core.esm-bundler.js:5234
processFragment @ runtime-core.esm-bundler.js:4915
patch @ runtime-core.esm-bundler.js:4511
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
patchBlockChildren @ runtime-core.esm-bundler.js:4835
processFragment @ runtime-core.esm-bundler.js:4896
patch @ runtime-core.esm-bundler.js:4511
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueJob @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5168
triggerEffects @ reactivity.esm-bundler.js:382
trigger @ reactivity.esm-bundler.js:352
set2 @ reactivity.esm-bundler.js:509
_createVNode.onClick._cache.<computed>._cache.<computed> @ Header.vue:8
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
Show 28 more frames
runtime-core.esm-bundler.js:38 [Vue warn]: Unhandled error during execution of watcher callback 
  at <VanPickerColumn value=undefined fields= {text: 'text', value: 'value', children: 'children'} options= {0: {…}, 1: {…}}  ... > 
  at <VanPicker ref="pickRef" columns= {0: {…}, 1: {…}} onConfirm=fn<bound onMenuSelect>  ... > 
  at <BaseTransition onAfterEnter=fn<onOpened> onAfterLeave=fn<onClosed> appear=false  ... > 
  at <Transition name="van-popup-slide-top" appear=false onAfterEnter=fn<onOpened>  ... > 
  at <VanPopup show=true onUpdate:show=fn position="top" > 
  at <Header title="标题" > 
  at <VodDetail onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:212
handleError @ runtime-core.esm-bundler.js:204
callWithErrorHandling @ runtime-core.esm-bundler.js:158
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
getter @ runtime-core.esm-bundler.js:1726
run @ reactivity.esm-bundler.js:185
doWatch @ runtime-core.esm-bundler.js:1834
watchEffect @ runtime-core.esm-bundler.js:1646
setup @ PickerColumn.js:161
callWithErrorHandling @ runtime-core.esm-bundler.js:155
setupStatefulComponent @ runtime-core.esm-bundler.js:7109
setupComponent @ runtime-core.esm-bundler.js:7064
mountComponent @ runtime-core.esm-bundler.js:4951
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
mountChildren @ runtime-core.esm-bundler.js:4714
processFragment @ runtime-core.esm-bundler.js:4885
patch @ runtime-core.esm-bundler.js:4511
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
componentUpdateFn @ runtime-core.esm-bundler.js:5066
run @ reactivity.esm-bundler.js:185
setupRenderEffect @ runtime-core.esm-bundler.js:5185
mountComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
mountChildren @ runtime-core.esm-bundler.js:4714
processFragment @ runtime-core.esm-bundler.js:4885
patch @ runtime-core.esm-bundler.js:4511
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
patchKeyedChildren @ runtime-core.esm-bundler.js:5291
patchChildren @ runtime-core.esm-bundler.js:5234
processFragment @ runtime-core.esm-bundler.js:4915
patch @ runtime-core.esm-bundler.js:4511
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
patchBlockChildren @ runtime-core.esm-bundler.js:4835
processFragment @ runtime-core.esm-bundler.js:4896
patch @ runtime-core.esm-bundler.js:4511
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueJob @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5168
triggerEffects @ reactivity.esm-bundler.js:382
trigger @ reactivity.esm-bundler.js:352
set2 @ reactivity.esm-bundler.js:509
_createVNode.onClick._cache.<computed>._cache.<computed> @ Header.vue:8
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
Show 36 more frames
runtime-core.esm-bundler.js:38 [Vue warn]: Unhandled error during execution of setup function 
  at <VanPickerColumn value=undefined fields= {text: 'text', value: 'value', children: 'children'} options= {0: {…}, 1: {…}}  ... > 
  at <VanPicker ref="pickRef" columns= {0: {…}, 1: {…}} onConfirm=fn<bound onMenuSelect>  ... > 
  at <BaseTransition onAfterEnter=fn<onOpened> onAfterLeave=fn<onClosed> appear=false  ... > 
  at <Transition name="van-popup-slide-top" appear=false onAfterEnter=fn<onOpened>  ... > 
  at <VanPopup show=true onUpdate:show=fn position="top" > 
  at <Header title="标题" > 
  at <VodDetail onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:212
handleError @ runtime-core.esm-bundler.js:204
callWithErrorHandling @ runtime-core.esm-bundler.js:158
setupStatefulComponent @ runtime-core.esm-bundler.js:7109
setupComponent @ runtime-core.esm-bundler.js:7064
mountComponent @ runtime-core.esm-bundler.js:4951
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
mountChildren @ runtime-core.esm-bundler.js:4714
processFragment @ runtime-core.esm-bundler.js:4885
patch @ runtime-core.esm-bundler.js:4511
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
componentUpdateFn @ runtime-core.esm-bundler.js:5066
run @ reactivity.esm-bundler.js:185
setupRenderEffect @ runtime-core.esm-bundler.js:5185
mountComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4926
patch @ runtime-core.esm-bundler.js:4518
mountChildren @ runtime-core.esm-bundler.js:4714
processFragment @ runtime-core.esm-bundler.js:4885
patch @ runtime-core.esm-bundler.js:4511
mountChildren @ runtime-core.esm-bundler.js:4714
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4595
patch @ runtime-core.esm-bundler.js:4515
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
patchKeyedChildren @ runtime-core.esm-bundler.js:5291
patchChildren @ runtime-core.esm-bundler.js:5234
processFragment @ runtime-core.esm-bundler.js:4915
patch @ runtime-core.esm-bundler.js:4511
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
updateComponent @ runtime-core.esm-bundler.js:4997
processComponent @ runtime-core.esm-bundler.js:4930
patch @ runtime-core.esm-bundler.js:4518
patchBlockChildren @ runtime-core.esm-bundler.js:4835
processFragment @ runtime-core.esm-bundler.js:4896
patch @ runtime-core.esm-bundler.js:4511
componentUpdateFn @ runtime-core.esm-bundler.js:5136
run @ reactivity.esm-bundler.js:185
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueJob @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5168
triggerEffects @ reactivity.esm-bundler.js:382
trigger @ reactivity.esm-bundler.js:352
set2 @ reactivity.esm-bundler.js:509
_createVNode.onClick._cache.<computed>._cache.<computed> @ Header.vue:8
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
Show 29 more frames
runtime-core.esm-bundler.js:38 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <VanPickerColumn value=undefined fields= {text: 'text', value: 'value', children: 'children'} options= {0: {…}, 1: {…}}  ... > 
  at <VanPicker ref="pickRef" columns= {0: {…}, 1: {…}} onConfirm=fn<bound onMenuSelect>  ... > 
  at <BaseTransition onAfterEnter=fn<onOpened> onAfterLeave=fn<onClosed> appear=false  ... > 
  at <Transition name="van-popup-slide-top" appear=false onAfterEnter=fn<onOpened>  ... > 
  at <VanPopup show=true onUpdate:show=fn position="top" > 
  at <Header title="标题" > 
  at <VodDetail onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:212
handleError @ runtime-core.esm-bundler.js:204
callWithErrorHandling @ runtime-core.esm-bundler.js:158
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueJob @ runtime-core.esm-bundler.js:279
(anonymous) @ runtime-core.esm-bundler.js:5168
triggerEffects @ reactivity.esm-bundler.js:382
trigger @ reactivity.esm-bundler.js:352
set2 @ reactivity.esm-bundler.js:509
_createVNode.onClick._cache.<computed>._cache.<computed> @ Header.vue:8
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
PickerColumn.js:162 Uncaught (in promise) TypeError: props.options.findIndex is not a function
    at PickerColumn.js:162:35
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at ReactiveEffect.getter [as fn] (runtime-core.esm-bundler.js:1726:24)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at doWatch (runtime-core.esm-bundler.js:1834:16)
    at watchEffect (runtime-core.esm-bundler.js:1646:12)
    at setup (PickerColumn.js:161:5)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7109:29)
```

### 重现步骤

```
<template>
  <van-notice-bar class="lo-notice-bar" left-icon="volume-o">本站本牛逼，请放心访问</van-notice-bar>
  <van-row gutter="5" class="lo-header">
    <van-col span="6"><router-link to="/"><h1 class="lo-header-h1">{{ title }}</h1></router-link></van-col>
    <van-col span="12"><Search /></van-col>
    <van-col span="6">
      <van-icon name="wap-nav" tag="div" class="lo-icon" @click="showMenu = true"><span class="lo-icon-span">所有栏目</span></van-icon>
      <van-icon name="wap-home" tag="div" class="lo-icon"><span class="lo-icon-span">首页</span></van-icon>
    </van-col>
  </van-row>
  <van-popup v-model:show="showMenu" position="top">
    <van-picker ref="pickRef" :columns="menus" @confirm="onMenuSelect" @cancel="showMenu = false" title="选择栏目" />
  </van-popup>
  <Menu />
</template>

<script>
import {Col, Row, NoticeBar, Tag, Icon, Picker, Popup, Toast} from 'vant'
import Search from './Search.vue'
import Menu from './Menu.vue'

export default {
  props: ['title'],
  data () {
    return {
      showMenu: false,
      menus: []
    }
  },
  provide() {
    // 使用函数的形式，可以访问到 `this`
    return {
      menus: this.menus
    }
  },
  components: {
    [NoticeBar.name]: NoticeBar,
    [Col.name]: Col,
    [Row.name]: Row,
    [Tag.name]: Tag,
    [Icon.name]: Icon,
    [Picker.name]: Picker,
    [Popup.name]: Popup,
    [Toast.name]: Toast,
    Search,
    Menu
  },
  methods: {
    onMenuSelect: ()=>{

    },
    getMenu() {
      this.$store.dispatch('getCore').then(res => {
        this.menus = res;
      });
    }
  },
  mounted() {
    this.getMenu();
  }
}


</script>

<style scoped>
</style>
```

### 设备/浏览器

vue3

**Comment by leafhina** [comment]
自行解决，是异步传过来的数据结构的问题
