### ISSUE TITLE
无法在nuxt@v3中生产环境使用，生产环境中使用的是mjs，无法引入组件

### ISSUE THREAD

**Issue by Vi-jay** [youzan/vant#10589]
### 重现链接

https://github.com/Vi-jay/vant-nuxt3.git

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

无法在nuxt@v3中生产环境使用，生产环境中使用的是mjs，无法引入组件

### 重现步骤

编译后无法打包

**Comment by chenjiahan** [comment]
Vant 有提供 lib/ssr.mjs 作为 nuxt.js 的入口，我试了下 build 是正常的，具体是哪块有问题？麻烦提供下详细描述

**Comment by Vi-jay** [comment]
> Vant 有提供 lib/ssr.mjs 作为 nuxt.js 的入口，我试了下 build 是正常的，具体是哪块有问题？麻烦提供下详细描述

请问有试过build之后运行吗？ 可以build 但是运行的时候会报错 无法导入模块

**Comment by xinconan** [comment]
试了下 build 之后运行确实会报错。
```bash
[nuxt] [request error] The requested module 'vant' does not provide an export named 'Button'
  at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)   
  at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)       
  at async Loader.import (internal/modules/esm/loader.js:178:24)
```

**Comment by hqwlkj** [comment]
我也遇到了同样的问题，目前有什么处理方法吗？
![image](https://user-images.githubusercontent.com/12181423/169961115-5f562df7-59cf-4590-94ef-c9bcf30d513f.png)
```


[nuxt] [request error] The requested module 'vant' does not provide an export named 'AddressEdit'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)  
  at async Loader.import (node:internal/modules/esm/loader:178:24)  
  at async ./server/chunks/handlers/renderer.mjs:11130:24  
  at async ./server/chunks/handlers/renderer.mjs:11186:64  
  at async ./server/node_modules/h3/dist/index.mjs:417:19  
  at async nodeHandler (./server/node_modules/h3/dist/index.mjs:367:7)  
  at async ufetch (./server/node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async $fetchRaw2 (./server/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async Object.errorhandler [as onError] (./server/chunks/nitro/node-server.mjs:317:16)
```

**Comment by hqwlkj** [comment]
> > 我也遇到了同样的问题，目前有什么处理方法吗？ ![image](https://user-images.githubusercontent.com/12181423/169961115-5f562df7-59cf-4590-94ef-c9bcf30d513f.png)
> > ```
> > 
> > 
> > [nuxt] [request error] The requested module 'vant' does not provide an export named 'AddressEdit'
> >   at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)  
> >   at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)  
> >   at async Loader.import (node:internal/modules/esm/loader:178:24)  
> >   at async ./server/chunks/handlers/renderer.mjs:11130:24  
> >   at async ./server/chunks/handlers/renderer.mjs:11186:64  
> >   at async ./server/node_modules/h3/dist/index.mjs:417:19  
> >   at async nodeHandler (./server/node_modules/h3/dist/index.mjs:367:7)  
> >   at async ufetch (./server/node_modules/unenv/runtime/fetch/index.mjs:9:17)  
> >   at async $fetchRaw2 (./server/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
> >   at async Object.errorhandler [as onError] (./server/chunks/nitro/node-server.mjs:317:16)
> > ```
> 
> 改一下源码的package.json可以运行，但是不支持按需加载，算了吧，nuxt3 能完全支持估计还要大半年

修改 vant 的源码还是谁的呢？我主要是验证一下可行性；麻烦提供一下你的处理方案，🙏🙏🙏🙏

**Comment by chenjiahan** [comment]
预计本周会处理

**Comment by hqwlkj** [comment]
> 预计本周会处理

十分感谢

**Comment by hqwlkj** [comment]
> 预计本周会处理

进度怎么样了，大佬。

**Comment by chenjiahan** [comment]
周末。

**Comment by chenjiahan** [comment]
目前 Vant 3.5.0-beta.1 版本已经将所有 esmodule 的代码及子依赖转换为 .mjs 后缀，在 vite/vue-cli 中都可以成功构建。

不过 nuxt3 还是有报错，从现象看是 nuxt3 没有正确解析 @vant/use 的入口文件，具体原因待排查。

![image](https://user-images.githubusercontent.com/7237365/170871485-dfea6f1b-737c-4f96-ad2a-0db6da6c920a.png)

**Comment by chenjiahan** [comment]
@vant/use 的问题已通过增加 exports field 解决

@hqwlkj 可以升级试一下

- vant@3.5.0-beta.1
- @vant/use 1.4.1
- @vant/popperjs 1.2.1

**Comment by hqwlkj** [comment]
> @vant/use 的问题已通过增加 exports field 解决

好的，马上出升级验证

**Comment by hqwlkj** [comment]
> * vant@3.5.0-beta.1
```

file:///Users/nuxt-ssr-app/node_modules/vant/es/utils/dom.mjs:1
import { useRect, useWindowSize } from "@vant/use";
         ^^^^^^^
SyntaxError: Named export 'useRect' not found. The requested module '@vant/use' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@vant/use';
const { useRect, useWindowSize } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async __instantiateModule__ (file:///Users/nuxt-ssr-app/.nuxt/dist/server/server.mjs:17091:3)
```


现在执行dev都报错了

```

"dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/sentry": "^5.1.7",
    "@vant/area-data": "^1.3.0",
    "@vant/use": "^1.4.1",
    "classnames": "^2.3.1",
    "js-cookie": "^3.0.1",
    "nuxt": "3.0.0-rc.3",
    "vant": "^3.5.0-beta.1",
    "vue": "^3.2.36"
  }
```

**Comment by hqwlkj** [comment]
> * @vant/popperjs

```

file:///Users/nuxt-ssr-app/node_modules/vant/es/utils/dom.mjs:1
import { useRect, useWindowSize } from "@vant/use";
         ^^^^^^^
SyntaxError: Named export 'useRect' not found. The requested module '@vant/use' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@vant/use';
const { useRect, useWindowSize } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async __instantiateModule__ (file:///Users/nuxt-ssr-app/.nuxt/dist/server/server.mjs:17091:3)


```
```


"dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/sentry": "^5.1.7",
    "@vant/area-data": "^1.3.0",
    "@vant/popperjs": "^1.2.1",
    "@vant/use": "^1.4.1",
    "classnames": "^2.3.1",
    "js-cookie": "^3.0.1",
    "nuxt": "3.0.0-rc.3",
    "vant": "^3.5.0-beta.1",
    "vue": "^3.2.36"
  },
```

现在执行 dev就报错了。

**Comment by chenjiahan** [comment]
确认 @vant/use 升级到 1.4.1 了？

**Comment by hqwlkj** [comment]
```
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@vant/area-data';
const { areaList } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
  at async ./server/chunks/handlers/renderer.mjs:11130:24  
  at async ./server/chunks/handlers/renderer.mjs:11186:64  
  at async ./server/node_modules/h3/dist/index.mjs:417:19  
  at async nodeHandler (./server/node_modules/h3/dist/index.mjs:367:7)  
  at async ufetch (./server/node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async $fetchRaw2 (./server/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
[nuxt] [request error] Named export 'areaList' not found. The requested module '@vant/area-data' is a CommonJS module, which may not support all module.exports as named exports.

```



```

TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (/Users/nuxt-ssr-app/.output/server/node_modules/vant/lib/vant.cjs.js:448:38)
    at setup (/Users/nuxt-ssr-app/.output/server/node_modules/vant/lib/vant.cjs.js:721:20)
    at callWithErrorHandling (file:///Users/nuxt-ssr-app/.output/server/chunks/handlers/renderer.mjs:2520:23)
    at setupStatefulComponent (file:///Users/nuxt-ssr-app/.output/server/chunks/handlers/renderer.mjs:8161:30)
    at setupComponent (file:///Users/nuxt-ssr-app/.output/server/chunks/handlers/renderer.mjs:8142:12)
    at renderComponentVNode (file:///Users/nuxt-ssr-app/.output/server/chunks/handlers/renderer.mjs:10487:17)
    at renderVNode (file:///Users/nuxt-ssr-app/.output/server/chunks/handlers/renderer.mjs:10610:22)
    at renderVNodeChildren (file:///Users/nuxt-ssr-app/.output/server/chunks/handlers/renderer.mjs:10625:9)
    at renderVNode (file:///Users/nuxt-ssr-app/.output/server/chunks/handlers/renderer.mjs:10602:13)
    at renderVNodeChildren (file:///Users/nuxt-ssr-app/.output/server/chunks/handlers/renderer.mjs:10625:9)
[Vue warn]: Component van-button is missing template or render function.

```

还是存在一些问题，希望在 v4 的基础上一并修复一下；因为项目是基于 `4.0.0-alpha.3 `版本开发的。

**Comment by chenjiahan** [comment]
@vant/area-data 后续会加一个 exports 来解决此问题。

v3 验证没问题后会合并到 v4 上

**Comment by hqwlkj** [comment]
> @vant/area-data 后续会加一个 exports 来解决此问题。
> 
> v3 验证没问题后会合并到 v4 上

今天能合并吗？我好验证一下 😄

**Comment by hqwlkj** [comment]
> @hqwlkj 已发布 4.0.0-alpha.4

更新了能正常启动了，但是还是会出现这个类型错误提示信息。
![image](https://user-images.githubusercontent.com/12181423/171207934-1019fddd-e940-4b7c-9598-4cfaa2dd2abc.png)

**Comment by chenjiahan** [comment]
@hqwlkj 给个最小复现仓库

**Comment by chenjiahan** [comment]
3.5.0 已正式发布

@hqwlkj 类型问题可以单独提个 issue，并提供复现方式，这个 issue 先 close 了

**Comment by leosin** [comment]
报告一下
nuxt 3-rc3
vant 3.5.0
在dev下可以浏览访问，也可以build，但不能generate生成html。

![image](https://user-images.githubusercontent.com/3676670/172848583-d33f2d2a-1c88-40a9-8ff1-434583cc19f5.png)

也是按这个方式配置的 `plugins/vant.ts` 但好像没有出现上面其他人的错误，我这个是什么错误呢？
```ts
import { defineNuxtPlugin } from '#app';
import Vant from 'vant';
import 'vant/lib/index.less';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(Vant);
});
```

**Comment by chenjiahan** [comment]
@leosin 可以提个 issue，提供一下最小复现仓库
