### ISSUE TITLE
在nuxt3下生成静态页时有报错，是都需要加client-only吗

### ISSUE THREAD

**Issue by leosin** [youzan/vant#10691]
### 重现链接

https://stackblitz.com/edit/nuxt-starter-owb6aa?file=app.vue

### Vant 版本

3.5.0

## yarn build 貌似是正常的

```bash
$ nuxt build
Nuxt CLI v3.0.0-rc.3
ℹ Client built in 2652ms
ℹ Building server...
✔ Server built in 869ms
✔ Generated public .output/public
start Building server...
ℹ Vite client warmed up in 4109ms
start Writing server bundle...
✔ Server built
  ├─ .output/server/package.json (553 B) (261 B gzip)
  ├─ .output/server/index.mjs (458 B) (255 B gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs.map (56.5 kB) (4.32 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs (15.7 kB) (5.09 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs.map (1.92 MB) (91.2 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs (431 kB) (98.6 kB gzip)
  ├─ .output/server/chunks/app/server.mjs.map (171 kB) (24.7 kB gzip)
  ├─ .output/server/chunks/app/server.mjs (146 kB) (36.8 kB gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs.map (358 B) (237 B gzip)
  └─ .output/server/chunks/app/client.manifest.mjs (314 B) (209 B gzip)
Σ Total size: 5.67 MB (931 kB gzip)
✔ You can preview this build using node .output/server/index.mjs
```

## yarn generate 是下面这样的。

```bash
$ nuxt generate
Nuxt CLI v3.0.0-rc.3                                                              11:13:08
ℹ Vite client warmed up in 1387ms                                                 11:13:13
ℹ Client built in 2501ms                                                          11:13:14
ℹ Building server...                                                              11:13:14
✔ Server built in 667ms                                                           11:13:15
✔ Generated public .output/public                                           nitro 11:13:15
ℹ Initializing prerenderer                                                  nitro 11:13:15
ℹ Prerendering 1 initial routes with crawler                                nitro 11:13:17

 WARN  [Vue warn]: Unhandled error during execution of setup function             11:13:17
  at <VanButton type="warning" class="px-4" onClick=fn<showPopup> >

 ERROR  [nuxt] [request error] Cannot read properties of null (reading 'proxy')   11:13:17
  at useRoute (./node_modules/vant/lib/vant.cjs.js:448:38)
  at setup (./node_modules/vant/lib/vant.cjs.js:721:20)
  at callWithErrorHandling (./.nuxt/prerender/chunks/renderer.mjs:2662:23)
  at setupStatefulComponent (./.nuxt/prerender/chunks/renderer.mjs:9556:30)
  at setupComponent (./.nuxt/prerender/chunks/renderer.mjs:9511:12)
  at renderComponentVNode (./.nuxt/prerender/chunks/renderer.mjs:12076:17)
  at Object.ssrRenderComponent (./.nuxt/prerender/chunks/renderer.mjs:12512:12)
  at eval (./.nuxt/prerender/chunks/app/server.mjs:3983:37)
  at renderComponentSubTree (./.nuxt/prerender/chunks/renderer.mjs:12157:13)
  at renderComponentVNode (./.nuxt/prerender/chunks/renderer.mjs:12092:16)

 ERROR  [unhandledRejection] Cannot read properties of null (reading 'proxy')     11:13:17

  at useRoute (node_modules/vant/lib/vant.cjs.js:448:38)
  at setup (node_modules/vant/lib/vant.cjs.js:721:20)
  at callWithErrorHandling (.nuxt/prerender/chunks/renderer.mjs:2662:23)
  at setupStatefulComponent (.nuxt/prerender/chunks/renderer.mjs:9556:30)
  at setupComponent (.nuxt/prerender/chunks/renderer.mjs:9511:12)
  at renderComponentVNode (.nuxt/prerender/chunks/renderer.mjs:12076:17)
  at Object.ssrRenderComponent (.nuxt/prerender/chunks/renderer.mjs:12512:12)
  at eval (.nuxt/prerender/chunks/app/server.mjs:3983:37)
  at renderComponentSubTree (.nuxt/prerender/chunks/renderer.mjs:12157:13)
  at renderComponentVNode (.nuxt/prerender/chunks/renderer.mjs:12092:16)

 ERROR  [nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of null (reading 'proxy')

  ├─ / (248ms) (Error: [500] Internal Server Error)                         nitro 11:13:17
✔ You can now deploy .output/public to any static hosting!
```

## 但加了`<client-only>`就可以打包了，我不确定这个是bug，还是只能这样写。目前还没写到异步获取数据那部分，不知道有其他大神写过类似的吗？能否有个标准的写法，新手求教:)

另外在别的框架讨论组里看到类似的解决方案，是加在`nuxt.config.ts`里的，不知道是否有用
```ts
const lifecycle = process.env.npm_lifecycle_event
export default defineNuxtConfig({
  build: {
    transpile:
      lifecycle === 'build' || lifecycle === 'generate' ? ['your-ui-framework-name'] : [],
  },
})
```

## 做了 3 个事情
1、在`plugins/vant.ts`里加了相关引入。
2、`nuxt.config.ts`里面加了 css 的引入
3、业务页面上写了组件内容
不知道哪里还需要做什么吗？

### 设备/浏览器

macOS / EDGE / Chrome

**Comment by leosin** [comment]
另外我看到nuxt3文档里写道插件的注册部分，plugins目录下，文件名可以分xxx.server.js或者xxx.client.js
但是我改成vant.client.ts却更加报错了，dev下面都报错。

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/173186045-da4588e8-df72-4935-8c47-d78dce71b823.png)

我在 stackblitz 里试了下没问题嘞

**Comment by leosin** [comment]
> 我在 stackblitz 里试了下没问题嘞
template里面你加了client-only了吗，好像是都要加这个才行。

**Comment by chenjiahan** [comment]
我没改链接里的任何内容
