### ISSUE TITLE
[Bug Report] 安卓6.0 系统打开白屏

### ISSUE THREAD

**Issue by yuxuewen** [youzan/vant#10765]
### 重现链接

https://github.com/yulimchen/vue3-h5-template.git

### Vant 版本

3.4.9

### 描述一下你遇到的问题。

在安卓6.0手机白屏
在3.4.1 版本已经以上环境会出现以下问题：

错误信息：
...

Unexpected token *

at Object.push../node_modules/vant/es/utils/format.js (http://xxxx:8080/js/chunk-vendors.js:3602:1)
at __webpack_require__ (http://10.100.251.54:8080/js/app.js:854:30)
at fn (http://10.100.251.54:8080/js/app.js:151:20)
at eval (webpack-internal:///./node_modules/vant/es/utils/create.js:6:65)
at Object.push../node_modules/vant/es/utils/create.js (http://10.100.251.54:8080/js/chunk-vendors.js:3566:1)
at __webpack_require__ (http://10.100.251.54:8080/js/app.js:854:30)
at fn (http://10.100.251.54:8080/js/app.js:151:20)
at eval (webpack-internal:///./node_modules/vant/es/utils/index.js:55:65)
at Object.push../node_modules/vant/es/utils/index.js (http://10.100.251.54:8080/js/chunk-vendors.js:3614:1)
at __webpack_require__ (http://10.100.251.54:8080/js/app.js:854:30)

### 重现步骤

下载项目
安装依赖
启动项目，在安卓6.0手机上 webview 打开链接

### 设备/浏览器

荣耀 PLK-AL10

**Comment by chenjiahan** [comment]
Vant 3 的兼容性与 Vue 3 一致，最低兼容到 chrome 53 版本。建议先检查一下 webview 对应的 chrome 版本是多少，可以查看 userAgent
