### ISSUE TITLE
nuxt3下 dev开发模式正常，build打包后异常

### ISSUE THREAD

**Issue by momtboy** [youzan/vant#10830]
### 重现链接

xx

### Vant 版本

3.5.2

### 描述一下你遇到的问题。

`[Vue warn]: provide() can only be used inside setup().
TypeError: Cannot read properties of null (reading 'proxy')
    at setup (/www/wwwroot/webapps/.output/server/node_modules/vant/lib/vant.cjs.js:5076:33)
    at callWithErrorHandling (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:2536:23)
    at setupStatefulComponent (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:8182:30)
    at setupComponent (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:8163:12)
    at renderComponentVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10510:17)
    at renderVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10633:22)
    at renderVNodeChildren (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10648:9)
    at renderVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10625:13)
    at renderVNodeChildren (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10648:9)
    at renderElementVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10699:17)
[Vue warn]: Component van-image is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (/www/wwwroot/webapps/.output/server/node_modules/vant/lib/vant.cjs.js:478:38)
    at setup (/www/wwwroot/webapps/.output/server/node_modules/vant/lib/vant.cjs.js:2278:20)
    at callWithErrorHandling (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:2536:23)
    at setupStatefulComponent (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:8182:30)
    at setupComponent (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:8163:12)
    at renderComponentVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10510:17)
    at renderVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10633:22)
    at renderVNodeChildren (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10648:9)
    at renderVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10625:13)
    at renderVNodeChildren (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10648:9)
[Vue warn]: Component van-cell is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (/www/wwwroot/webapps/.output/server/node_modules/vant/lib/vant.cjs.js:478:38)
    at setup (/www/wwwroot/webapps/.output/server/node_modules/vant/lib/vant.cjs.js:2278:20)
    at callWithErrorHandling (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:2536:23)
    at setupStatefulComponent (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:8182:30)
    at setupComponent (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:8163:12)
    at renderComponentVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10510:17)
    at renderVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10633:22)
    at renderVNodeChildren (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10648:9)
    at renderVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10625:13)
    at renderVNodeChildren (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10648:9)
[Vue warn]: Component van-cell is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (/www/wwwroot/webapps/.output/server/node_modules/vant/lib/vant.cjs.js:478:38)
    at setup (/www/wwwroot/webapps/.output/server/node_modules/vant/lib/vant.cjs.js:2278:20)
    at callWithErrorHandling (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:2536:23)
    at setupStatefulComponent (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:8182:30)
    at setupComponent (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:8163:12)
    at renderComponentVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10510:17)
    at renderVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10633:22)
    at renderVNodeChildren (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10648:9)
    at renderVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10625:13)
    at renderVNodeChildren (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10648:9)
[Vue warn]: Component van-cell is missing template or render function.
TypeError: Cannot read properties of null (reading 'proxy')
    at useRoute (/www/wwwroot/webapps/.output/server/node_modules/vant/lib/vant.cjs.js:478:38)
    at setup (/www/wwwroot/webapps/.output/server/node_modules/vant/lib/vant.cjs.js:751:20)
    at callWithErrorHandling (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:2536:23)
    at setupStatefulComponent (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:8182:30)
    at setupComponent (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:8163:12)
    at renderComponentVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10510:17)
    at renderVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10633:22)
    at renderVNodeChildren (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10648:9)
    at renderVNode (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10625:13)
    at renderVNodeChildren (file:///www/wwwroot/webapps/.output/server/chunks/handlers/renderer.mjs:10648:9)
[Vue warn]: Component van-button is missing template or render function.
[nuxt] [request error] Cannot read properties of null (reading 'proxy')
  at setup (./.output/server/node_modules/vant/lib/vant.cjs.js:5076:33)  
  at callWithErrorHandling (./.output/server/chunks/handlers/renderer.mjs:2536:23)  
  at setupStatefulComponent (./.output/server/chunks/handlers/renderer.mjs:8182:30)  
  at setupComponent (./.output/server/chunks/handlers/renderer.mjs:8163:12)  
  at renderComponentVNode (./.output/server/chunks/handlers/renderer.mjs:10510:17)  
  at renderVNode (./.output/server/chunks/handlers/renderer.mjs:10633:22)  
  at renderVNodeChildren (./.output/server/chunks/handlers/renderer.mjs:10648:9)  
  at renderVNode (./.output/server/chunks/handlers/renderer.mjs:10625:13)  
  at renderVNodeChildren (./.output/server/chunks/handlers/renderer.mjs:10648:9)  
  at renderElementVNode (./.output/server/chunks/handlers/renderer.mjs:10699:17)
`

### 重现步骤

1. nuxt  版本 v3.0.0-rc.5
2. npm run build
3. npm run start

### 设备/浏览器

windows

**Comment by momtboy** [comment]
[https://github.com/vant-ui/vant-demo/issues/97](https://github.com/vant-ui/vant-demo/issues/97)

**Comment by chenjiahan** [comment]
未能复现，麻烦提供复现问题的仓库和复现步骤哈
