### ISSUE TITLE
[Bug Report] vant-cli-6.0打包报错

### ISSUE THREAD

**Issue by sukebin** [youzan/vant#11626]
### 重现链接

https://github.com/sukebin/vant-cli-test

### Vant Cli 版本

6.0.0

### 描述一下你遇到的问题。

使用vant-cli的6.0.0版本打包报错，不确定是rollup问题还是新版vant-cli问题，麻烦确定下
报错内容

TypeError: Cannot read property 'suggestedVariableName' of undefined
    at Object.deconflictImportsOther (file:///D:/git/sm-form-libraryV3/node_modules/rollup/dist/es/shared/node-entry.js:14740:48)
    at deconflictChunk (file:///D:/git/sm-form-libraryV3/node_modules/rollup/dist/es/shared/node-entry.js:14705:52)
    at Chunk.setIdentifierRenderResolutions (file:///D:/git/sm-form-libraryV3/node_modules/rollup/dist/es/shared/node-entry.js:15977:9)
    at Chunk.renderModules (file:///D:/git/sm-form-libraryV3/node_modules/rollup/dist/es/shared/node-entry.js:15836:14)
    at Chunk.render (file:///D:/git/sm-form-libraryV3/node_modules/rollup/dist/es/shared/node-entry.js:15367:111)
    at file:///D:/git/sm-form-libraryV3/node_modules/rollup/dist/es/shared/node-entry.js:16981:72
    at Array.map (<anonymous>)
    at renderChunks (file:///D:/git/sm-form-libraryV3/node_modules/rollup/dist/es/shared/node-entry.js:16981:53)
    at Bundle.generate (file:///D:/git/sm-form-libraryV3/node_modules/rollup/dist/es/shared/node-entry.js:17207:19)
    at async file:///D:/git/sm-form-libraryV3/node_modules/rollup/dist/es/shared/node-entry.js:25442:27

### 重现步骤

拉下仓库，使用yarn build打包会报错
但是删除sm-input或者sm-editor-text其中一个文件夹，在yarn build打包就不会报错

**Comment by chenjiahan** [comment]
从错误堆栈看，是 rollup 代码在报错，建议自行排查下，或者到 rollup 仓库下提个 issue 问问呢
