### ISSUE TITLE
[Bug Report]vue3+vite+ts项目，引入vant4报错：Cannot read properties of null (reading 'proxy')

### ISSUE THREAD

**Issue by qifengwangye** [youzan/vant#11624]
### 重现链接

因为没有github仓库，因此使用百度云传递本地代码
https://pan.baidu.com/s/1ep18nTk3wz-hZGy2fMetnw?pwd=9utp

### Vant 版本

4.0.11

### 描述一下你遇到的问题。

引入vant4组件，启动项目之后，页面报错
```js
Cannot read properties of null (reading 'proxy')
    at useRoute (use-route.mjs:22:33)
    at setup (Cell.mjs:35:19)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
    at setupComponent (runtime-core.esm-bundler.js:7120:11)
    at mountComponent (runtime-core.esm-bundler.js:5473:13)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
    at mountChildren (runtime-core.esm-bundler.js:5234:13)
    at processFragment (runtime-core.esm-bundler.js:5407:13)
```

### 重现步骤

npm start
启动后修改访问地址为：http://127.0.0.1:19168/#/WEB_APP/frontendKnowledge/main

！！！补充：在 frontendKnowledge/main/index.tsx文件中引入并使用vant的button或者cell组件

打开控制台即可看到报错

### 设备/浏览器

chrome，edge

**Comment by wjw-gavin** [comment]
我这运行正常哦
你是不是签入到App壳子里，运行环境版本过低不支持 `proxy `

![image](https://user-images.githubusercontent.com/19986739/221546102-b61ff554-4437-4dc2-8fb4-f42c51939894.png)

**Comment by qifengwangye** [comment]
> 我这运行正常哦 你是不是签入到App壳子里，运行环境版本过低不支持 `proxy `
> 
> ![image](https://user-images.githubusercontent.com/19986739/221546102-b61ff554-4437-4dc2-8fb4-f42c51939894.png)

请问你是使用了vant的组件呢，我是使用vant的组件不展示，并且报错

**Comment by wjw-gavin** [comment]
正常哈
![image](https://user-images.githubusercontent.com/19986739/221735517-1238be68-0bc6-4e7f-94c3-00c6f93d503d.png)

![image](https://user-images.githubusercontent.com/19986739/221735455-d521e675-2978-4c77-9cfc-8936a15188d6.png)

**Comment by qifengwangye** [comment]
重装了一下依赖，可以了T_T，感谢指教
