### ISSUE TITLE
popup配合picker使用，打包后报错

### ISSUE THREAD

**Issue by yc0123450** [youzan/vant#11823]
### 重现链接

暂无

### Vant 版本

2.12.54

### 描述一下你遇到的问题。

开发环境是正常的，但是打包上线后，跳转到新页面报错如下：

chunk-vendors.51240e31.js:27 Uncaught (in promise) TypeError: Cannot read properties of null (reading '1')
    at e.getFmpTime (chunk-vendors.51240e31.js:27:259462)
    at e.calculateFinalScore (chunk-vendors.51240e31.js:27:258836)
    at e.initObserver (chunk-vendors.51240e31.js:27:258411)
    at new e (chunk-vendors.51240e31.js:27:257862)
    at e.<anonymous> (chunk-vendors.51240e31.js:27:263128)
    at chunk-vendors.51240e31.js:27:262916
    at Object.next (chunk-vendors.51240e31.js:27:263021)
    at chunk-vendors.51240e31.js:27:263810
    at new Promise (<anonymous>)
    at e.recordPerf (chunk-vendors.51240e31.js:27:263546)

点开具体报错位置可以看到是变量u为null，下标1取不到值，请问这个方法作用是什么，可能报错原因是什么
![image](https://user-images.githubusercontent.com/26277752/236609096-bb5b0ad6-8494-47f4-9cfb-3a5fd68855b0.png)

### 重现步骤

点击按钮，弹出下拉选项，选中一个点击确认，跳转到新页面，此时控制台报错如上，虽然报错但不影响后续业务代码执行

### 设备/浏览器

谷歌浏览器，微信内访问

**Comment by chenjiahan** [comment]
截图中的报错代码并不是 Vant 组件的代码喔，Vant 里并尅有 getFmpTime 这个方法，建议自行排查下

**Comment by yc0123450** [comment]
好的，谢谢
