### ISSUE TITLE
在vue-ssr（非nuxt）下组件使用出现问题

### ISSUE THREAD

**Issue by xanggang** [youzan/vant#1261]
基于https://github.com/vuejs/vue-hackernews-2.0 搭建的ssr项目， 在entry-client中加载插件
```
import Vant from 'vant'
import 'vant/lib/vant-css/index.css'
Vue.use(Vant)
```

控制台```The client-side rendered virtual DOM tree is not matching server-rendered content.``` 

 如果直接在app.js中引入vant , 控制台报错
```
[2018-06-11T15:35:08.418] [ERROR] error - ReferenceError: window is not defined
    at server-bundle.js:1075:2
    at server-bundle.js:1064:46
    at module.exports.module.exports (node_modules/style-loader/lib/addStyles.js:77:0)
    at Object.<anonymous> (node_modules/vant/lib/vant-css/index.css?291d:16:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 10991803226e4a90b421:25:0)
    at Object.<anonymous> (server-bundle.js:508:86)
    at __webpack_require__ (webpack:/webpack/bootstrap 10991803226e4a90b421:25:0)
    at Object.module.exports.__webpack_exports__.a (server-bundle.js:424:63)
    at __webpack_require__ (webpack:/webpack/bootstrap 10991803226e4a90b421:25:0)
    at server-bundle.js:92:18
```

**Comment by chenjiahan** [comment]
能否提供一个复现问题的 git 仓库？

**Comment by vonweb** [comment]
@chenjiahan 能出一个ssr的demo吗，我也遇到一样的问题
如果entry-client引入
![image](https://user-images.githubusercontent.com/5784758/42213699-1f3503bc-7eec-11e8-805a-564229f017d3.png)，在浏览器看到的html，组件没有处理
![image](https://user-images.githubusercontent.com/5784758/42213778-4e22bf0c-7eec-11e8-8832-e4178965cd81.png)
@xanggang 你现在解决了吗

**Comment by xanggang** [comment]
@vonweb 并没能解决， 之后我是用nuxt来重构了项目。

我重新初始化的https://github.com/vuejs/vue-hackernews-2.0项目根本无法启动， 所以未能提供demo。

**Comment by vonweb** [comment]
@xanggang 谢谢
vue-hackernews不能启动现象，你是不是使用yarn安装的，把vue-hackernews项目目录下的yarn.lock与node_modules删掉，重新安装就好了
