### ISSUE TITLE
uniapp+vant+vue2真机运行出现userAgent没有定义的错误

### ISSUE THREAD

**Issue by suolong182** [youzan/vant#12969]
### Reproduction Link

https://gitee.com/suolong182/shop-h5.git

### Vant Version

"vant": "^2.13.2"

### Describe the Bug

使用若依的移动端框架+vant2+vue2+uniapp，在真机运行时会报错，报错如下：
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'userAgent' of undefined
 at isIOS (app-service.js:14002:69)
 at  (app-service.js:13970:31)
 at __webpack_require__ (app-service.js:80:30)
 at  (app-service.js:13377:20)
 at __webpack_require__ (app-service.js:80:30)
 at  (app-service.js:11488:37)
 at __webpack_require__ (app-service.js:80:30)
 at  (app-service.js:9268:43)
 at __webpack_require__ (app-service.js:80:30)
 at eval (<anonymous>:11:36)
![image](https://github.com/youzan/vant/assets/167269201/8e5742b6-80c7-40c4-b558-0bc5bf6a5ca3)

### Reproduce Steps

![image](https://github.com/youzan/vant/assets/167269201/78f62ff1-06e5-455c-838f-a4f7044e28f3)

**Comment by 13114871605** [comment]
有人解决吗
