### ISSUE TITLE
引入index.css文件之后会导致vue内存溢出崩溃

### ISSUE THREAD

**Issue by hst19960721** [youzan/vant#12983]
### 重现链接

https://codesandbox.io/p/devbox/vant-4-issue-template-8fuq5o?file=%2Fsrc%2FApp.vue%3A10%2C9

### Vant 版本

4.9.1

### 描述一下你遇到的问题。

环境为：
      noedjs:18.16.0（nvm下载)
      vue/cli:5.0.8
      vue:3.2.13
      vant:4.9.1

在main.js引入index.css文件之后会导致vue运行崩溃，报错代码如下：

`RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at stringify (D:\nvm\v18.16.0\node_modules\@vue\cli\node_modules\jsonfile\utils.js:3:20)
    at Object._writeFile (D:\nvm\v18.16.0\node_modules\@vue\cli\node_modules\jsonfile\index.js:66:15)
    at Object._writeFile (D:\nvm\v18.16.0\node_modules\@vue\cli\node_modules\universalify\index.js:18:45)
    at writeOnDisk (D:\nvm\v18.16.0\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\shared-data.js:87:12)
    at async Object.set (D:\nvm\v18.16.0\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\shared-data.js:57:5)

Node.js v18.16.0`

### 重现步骤

引入vant4.9.1版本就会导致出现这个问题
完全不知道是哪里出了问题，网上也搜索不到任何BUG相关记录。

**Comment by chenjiahan** [comment]
未能复现该问题，如果是 Vue CLI 项目，建议考虑切换到 Rsbuild 或 Vite

https://rsbuild.dev/zh/guide/migration/vue-cli
