### ISSUE TITLE
使用babel-plugin-import 报错

### ISSUE THREAD

**Issue by 5kinna** [youzan/vant#1815]
已确认安装了依赖babel-plugin-import ，配置如下：

{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2",
    ["import", { "libraryName": "vant", "style": true }]
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime"]
}

执行命令 yarn dev后报错，错误提示如下：

Failed to compile with 2 errors                                                                                                                                                                     13:36:34
 error  in (webpack)-dev-server/client?http://localhost:8080

Module build failed: Error: Couldn't find preset "import" relative to directory "D:\\work\\pros\\sass_mobi"
    at D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\work\pros\sass_mobi\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (D:\work\pros\sass_mobi\node_modules\babel-loader\lib\index.js:173:20)

 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./src/main.js

Module build failed: Error: Couldn't find preset "import" relative to directory "D:\\work\\pros\\sass_mobi"
    at D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\work\pros\sass_mobi\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\work\pros\sass_mobi\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (D:\work\pros\sass_mobi\node_modules\babel-loader\lib\index.js:173:20)

 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by chenjiahan** [comment]
这个问题跟 Vant 没有关系，建议看下你的插件是否正确安装到了对应的目录
