### ISSUE TITLE
Unknown plugin "external-helpers"

### ISSUE THREAD

**Issue by dabinghao123** [youzan/vant#3000]
**Describe the bug**
安装vant后运行报这个错
VM61719:1 ./node_modules/vue-lazyload/vue-lazyload.js
Module build failed: ReferenceError: Unknown plugin "external-helpers" specified in "/Users/huangbing/Desktop/shikeeLiveHotel/newLiveHotel/node_modules/vue-lazyload/.babelrc" at 0, attempted to resolve relative to "/Users/huangbing/Desktop/shikeeLiveHotel/newLiveHotel/node_modules/vue-lazyload"
    at /Users/huangbing/Desktop/shikeeLiveHotel/newLiveHotel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17

**Screenshots**
![image](https://user-images.githubusercontent.com/4270322/54595485-ae705980-4a6d-11e9-9c5b-97adf90ba1fa.png)

**Environment**
 - Device: macbook pro 13
 - Browser: chrome
 - Vant Version: 1.6.10

**Reproduce**

**Comment by dabinghao123** [comment]
> **Describe the bug**
> 安装vant后运行报这个错
> VM61719:1 ./node_modules/vue-lazyload/vue-lazyload.js
> Module build failed: ReferenceError: Unknown plugin "external-helpers" specified in "/Users/huangbing/Desktop/shikeeLiveHotel/newLiveHotel/node_modules/vue-lazyload/.babelrc" at 0, attempted to resolve relative to "/Users/huangbing/Desktop/shikeeLiveHotel/newLiveHotel/node_modules/vue-lazyload"
> at /Users/huangbing/Desktop/shikeeLiveHotel/newLiveHotel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/4270322/54595485-ae705980-4a6d-11e9-9c5b-97adf90ba1fa.png)
> 
> **Environment**
> 
> * Device: macbook pro 13
> * Browser: chrome
> * Vant Version: 1.6.10
> 
> **Reproduce**
