### ISSUE TITLE
自动引入/手动引入组件都不支持nuxt服务端渲染

### ISSUE THREAD

**Issue by ranwawa** [youzan/vant#4436]
示例代码
https://codesandbox.io/embed/codesandbox-nuxt-vant-f6200

当yarn run generate时就会报错
```
 ERROR   /                                                                        11:53:22

/sandbox/node_modules/vant/lib/style/base.css:1
(function (exports, require, module, __filename, __dirname) { @-webkit-keyframes van-slide-up-enter{0%{-webkit-transform:translate3d(0,100%,0);transform:translate3d(0,100%,0)}}@keyframes van-slide-up-enter{0%{-webkit-transform:translate3d(0,100%,0);transform:translate3d(0,100%,0)}}@-webkit-keyframes van-slide-up-leave{to{-webkit-transform:translate3d(0,100%,0);transform:translate3d(0,100%,0)}}@keyframes van-slide-up-leave{to{-webkit-transform:translate3d(0,100%,0);transform:translate3d(0,100%,0)}}@-webkit-keyframes van-slide-down-enter{0%{-webkit-transform:translate3d(0,-100%,0);transform:translate3d(0,-100%,0)}}@keyframes van-slide-down-enter{0%{-webkit-transform:translate3d(0,-100%,0);transform:translate3d(0,-100%,0)}}@-webkit-keyframes van-slide-down-leave{to{-webkit-transform:translate3d(0,-100%,0);transform:translate3d(0,-100%,0)}}@keyframes van-slide-down-leave{to{-webkit-transform:translate3d(0,-100%,0);transform:translate3d(0,-100%,0)}}@-webkit-keyfram

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at createScript (vm.js:277:10)
    at Object.runInThisContext (vm.js:329:10)
    at Module._compile (internal/modules/cjs/loader.js:710:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/sandbox/node_modules/vant/lib/button/style/index.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

或者，如果有多个页面，在非入口页面引入了vant组件，网址里面直接访问这个引用了vant组件的页面时，就会报错
![image](https://user-images.githubusercontent.com/30344590/64695188-24f68d00-d4ce-11e9-8b1a-49a69d65faea.png)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/782

**Comment by ranwawa** [comment]
> 参见 #782

没看懂。
我是手动引入的组件。。样式也是正常引入的。。
dev和build能够正常访问。
但是generate的时候会报错~！~
所以这个报错不用理？

**Comment by gp0320** [comment]
配置这样写：
`

  build: {
   // 添加这个是关键，添加后babel才会处理依赖包vant里面的代码
    transpile: [ /vant.*?less/ ], 
   
    babel: {
      plugins: [
        ['import', {
          libraryName: 'vant',
          "style": (name) => {
            return `${name}/style/less.js`
          }
        }, 'vant']
      ],
    },
  }

`
具体参考我的文章：
https://juejin.im/post/5e012778518825127f085da8
