### ISSUE TITLE
[Bug Report] Popup关于beforeDestoryr的bug

### ISSUE THREAD

**Issue by aosnow** [youzan/vant#4760]
### 设备 / 浏览器
iphone8p/chrome

### Vant 版本
2.2.6

### Vue版本
2.6.10

### 重现链接
<a href="https://youzan.github.io/vant-issue-generater/dist/#/zh-CN" target="_blank">https://youzan.github.io/vant-issue-generater/dist/#/zh-CN</a>

### 描述问题
Popup 关于 beforeDestory 里面的错误，每次在勾子生效时都会报错：
```
vue.esm.js?a026:628 [Vue warn]: Error in beforeDestroy hook: "HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent."

found in

---> <VanPopup>
       <PopupBase> at src/components/popup/PopupBase.vue
         <RecommendDishes> at src/views/my-order/RecommendDishes.vue
           <OrderEvaluate> at src/views/my-order/OrderEvaluate.vue
             <App> at src/App.vue
               <Root>

vue.esm.js?a026:1897 DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at VueComponent.beforeDestroy (webpack-internal:///./node_modules/vant/es/mixins/popup/index.js:82:24)
    at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.esm.js:1862:57)
    at callHook (webpack-internal:///./node_modules/vue/dist/vue.esm.js:4216:7)
    at VueComponent.Vue.$destroy (webpack-internal:///./node_modules/vue/dist/vue.esm.js:3975:5)
    at destroy (webpack-internal:///./node_modules/vue/dist/vue.esm.js:3165:27)
    at invokeDestroyHook (webpack-internal:///./node_modules/vue/dist/vue.esm.js:6109:59)
    at VueComponent.patch [as __patch__] (webpack-internal:///./node_modules/vue/dist/vue.esm.js:6462:30)
    at VueComponent.Vue.$destroy (webpack-internal:///./node_modules/vue/dist/vue.esm.js:3998:8)
    at destroy (webpack-internal:///./node_modules/vue/dist/vue.esm.js:3165:27)
    at invokeDestroyHook (webpack-internal:///./node_modules/vue/dist/vue.esm.js:6109:59)
```

出错的代码:
```
import { PopupMixin } from '../mixins/popup';

...
// 70~76 行：
  beforeDestroy: function beforeDestroy() {
    this.close();

    if (this.getContainer && this.$parent && this.$parent.$el) {
      this.$parent.$el.appendChild(this.$el);
    }
  }
...
```

请赐教，实在看不懂这句的目的是什么？

**Comment by aosnow** [comment]
设置 getContainer 为 'body' 的目的是为了解决叠加弹层时 overlay 遮罩层消失的问题，但是设置后会出现上面的错误。

**Comment by chenjiahan** [comment]
能否提供一下复现的 codesandbox 链接

**Comment by aosnow** [comment]
不需要的，任何一个页面只要有用到 popup 组件，在 webpack-dev-server 环境下就可以看到，每次有 hot-update 就会在 console 出现大量的报错。
其实叠加的遮罩层处理，你们做的太复杂的，完全没必要复用js去动态处理当前overlay的z-index
```
// 以下是利用定位来解决遮罩层叠加的方法，推荐你们可以采纳，可以节省很多代码和开销
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,viewport-fit=cover">
  <title>aaa</title>
  <style>
  body {
    background: #ffffff;
  }

  .dialog {
    position: fixed;
    left: 0;
    top: 0;
    width: 100vw;
    height: 100vh;
  }

  .dialog__overlay {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.2);
    z-index: 1000;
  }

  .dialog__content {
    width: 100%;
    border: 1px solid #cccccc;
    background: #ffffff;
    position: absolute;
    bottom: 0;
    left: 0;
    padding: 20px;
    z-index: 2000;
  }
  </style>
</head>
<body>
  <h2>替换数组</h2>
  <p>变异方法，顾名思义，会改变调用了这些方法的原始数组。相比之下，也有非变异 (non-mutating method) 方法，例如 filter()、concat() 和 slice() 。它们不会改变原始数组，而总是返回一个新数组。</p>
  <div class="dialog">
    <div class="dialog__overlay"></div>
    <div class="dialog__content">
      <p>content</p>
      <p>content</p>
      <p>content</p>
    </div>
  </div>

  <div class="dialog">
    <div class="dialog__overlay"></div>
    <div class="dialog__content">
      <p>content</p>
      <p>content</p>
    </div>
  </div>

  <div class="dialog">
    <div class="dialog__overlay"></div>
    <div class="dialog__content">
      <p>content</p>
    </div>
  </div>
</body>
</html>
```

**Comment by aosnow** [comment]
> 能否提供一下复现的 codesandbox 链接

应该是至少存在一种情况，若 Popup 的实例一次也没有打开过，即并没有加入到 document 中，那这个 beforeDestroy 的逻辑应该就会存在一些不足之处。

**Comment by chenjiahan** [comment]
> 其实叠加的遮罩层处理，你们做的太复杂的，完全没必要复用js去动态处理当前overlay的z-index

实际场景比较复杂，不管理 z-index 很难做到正确的层级叠加

> 应该是至少存在一种情况，若 Popup 的实例一次也没有打开过，即并没有加入到 document 中，那这个 beforeDestroy 的逻辑应该就会存在一些不足之处。

这种情况我试了下没问题，麻烦提供下 codesandbox 链接吧

**Comment by aosnow** [comment]
上面不是提供源码了么。。。。就是叠加的实现，没有任何js就实现了，这个在weui也有利用这点实现叠加。

1、随便在个空白vue页添加一个Popup组件，然后在webpack-dev-server环境下，随便改个var触发hotupdate就看到报错。
2、在生产环境下，只要碰到路由跳转，就会报错，如a页面有Popup，我不去打开，然后直接跳转到b页面，就会触发beforeDestroy，这不需要源码都能想象得到吧，在里面关于$el的操作如果没加入到document就不会有$parent

**Comment by oymj** [comment]
我也遇到这个问题，Popup封装为组件使用时，设置getContainer为 'body' 报同样的错
`vue.runtime.esm.js?2b0e:1888 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at VueComponent.beforeDestroy (webpack-internal:///./node_modules/vant/es/mixins/popup/index.js:82:24)
    at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1853:57)
    at callHook (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4207:7)
    at VueComponent.Vue.$destroy (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3966:5)
    at destroy (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3156:27)
    at invokeDestroyHook (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6098:59)
    at VueComponent.patch [as __patch__] (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6451:30)
    at VueComponent.Vue.$destroy (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3989:8)
    at destroy (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3156:27)
    at invokeDestroyHook (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6098:59)`

**Comment by aosnow** [comment]
这是复现链接：https://codesandbox.io/s/vant-issue-moban-hcu8y
总结了下原因，就是 Popup 如果进行二次封装就会报错。

**Comment by oymj** [comment]
确实二次封装后的会有这个问题，还有点击浏览器后退时Popup不会关闭

**Comment by ymjdev** [comment]
是否有解决方案？影响线上使用了 @chenjiahan

**Comment by chenjiahan** [comment]
目前 Vue 里移动组件的根节点会抛出错误提示。

因此二次封装 Popup 组件，且使用 get-container 时，需要在 Popup 外层套一个 div 标签，就可以解决这个问题

**Comment by ymjdev** [comment]
> 目前 Vue 里移动组件的根节点 DOM 时会抛出错误提示。
> 
> 因此二次封装 Popup 组件，且使用 get-container 时，需要在 Popup 外层套一个 div 标签，就可以解决这个问题

加了div不报错了，但是点击浏览器后退Popup并不会关闭啊

**Comment by chenjiahan** [comment]
@ymjdev 下个版本会加一个 close-on-popstate 属性

**Comment by JustGogoing** [comment]
父组件将ref传递给子组件 子组件关闭时也报同样的错...
`
<van-sku
     *********
      :get-container="() => el"
      ref="sku"
    >
      <div slot="sku-messages"></div>
    </van-sku>

props: {
    el: {
      type: Element,
      required: true
    }
  },
`
