### ISSUE TITLE
[Bug Report] Popup组件封装组件使用路由后退报错且无法关闭

### ISSUE THREAD

**Issue by oymj** [youzan/vant#4798]
### 设备 / 浏览器
chorme 77 / 微信内部浏览器

### Vant 版本
2.2.8

### Vue版本
2.6.10

### 重现链接
<a href="https://codesandbox.io/s/vant-issue-moban-hcu8y" target="_blank">https://codesandbox.io/s/vant-issue-moban-hcu8y</a>

### 描述问题
Popup组件封装组件使用路由后退报错且无法关闭
操作方式： 点击"跳转到弹窗页" => 点击 "打开弹窗" => 点击浏览器后退
错误：
```
proxyConsole.js:72 [Vue warn]: Error in beforeDestroy hook: "HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent."

found in

---> <VanPopup>
       <PopupBase> at /src/PopupBase.vue
         <Popup> at /src/popup.vue
           <App> at /src/App.vue
             <Root>
console.<computed> @ proxyConsole.js:72
r.config.warnHandler @ index.js:61
warn @ vue.common.dev.js:628
logError @ vue.common.dev.js:1889
globalHandleError @ vue.common.dev.js:1884
handleError @ vue.common.dev.js:1844
invokeWithErrorHandling @ vue.common.dev.js:1867
callHook @ vue.common.dev.js:4210
Vue.$destroy @ vue.common.dev.js:3969
destroy @ vue.runtime.esm.js? [sm]:3159
invokeDestroyHook @ vue.runtime.esm.js? [sm]:6108
patch @ vue.runtime.esm.js? [sm]:6461
Vue.$destroy @ vue.runtime.esm.js? [sm]:3995
destroy @ vue.runtime.esm.js? [sm]:3159
invokeDestroyHook @ vue.runtime.esm.js? [sm]:6108
invokeDestroyHook @ vue.runtime.esm.js? [sm]:6113
patch @ vue.runtime.esm.js? [sm]:6461
Vue.$destroy @ vue.runtime.esm.js? [sm]:3995
destroy @ vue.runtime.esm.js? [sm]:3159
invokeDestroyHook @ vue.runtime.esm.js? [sm]:6108
removeVnodes @ vue.runtime.esm.js? [sm]:6124
updateChildren @ vue.runtime.esm.js? [sm]:6229
patchVnode @ vue.runtime.esm.js? [sm]:6313
patch @ vue.runtime.esm.js? [sm]:6476
Vue._update @ vue.runtime.esm.js? [sm]:3942
updateComponent @ vue.runtime.esm.js? [sm]:4060
get @ vue.runtime.esm.js? [sm]:4473
run @ vue.runtime.esm.js? [sm]:4548
flushSchedulerQueue @ vue.runtime.esm.js? [sm]:4304
eval @ vue.runtime.esm.js? [sm]:1980
flushCallbacks @ vue.runtime.esm.js? [sm]:1906
characterData (async)
timerFunc @ vue.runtime.esm.js? [sm]:1958
nextTick @ vue.runtime.esm.js? [sm]:1990
queueWatcher @ vue.runtime.esm.js? [sm]:4396
update @ vue.runtime.esm.js? [sm]:4538
notify @ vue.runtime.esm.js? [sm]:730
reactiveSetter @ vue.runtime.esm.js? [sm]:1055
eval @ vue-router.common.js:2750
eval @ vue-router.common.js:2749
updateRoute @ vue-router.common.js:2176
eval @ vue-router.common.js:2039
eval @ vue-router.common.js:2161
step @ vue-router.common.js:1845
step @ vue-router.common.js:1852
runQueue @ vue-router.common.js:1856
eval @ vue-router.common.js:2156
step @ vue-router.common.js:1845
eval @ vue-router.common.js:1849
eval @ vue-router.common.js:2141
eval @ vue-router.common.js:1923
iterator @ vue-router.common.js:2122
step @ vue-router.common.js:1848
step @ vue-router.common.js:1852
step @ vue-router.common.js:1852
runQueue @ vue-router.common.js:1856
confirmTransition @ vue-router.common.js:2149
transitionTo @ vue-router.common.js:2036
eval @ vue-router.common.js:2444
proxyConsole.js:72 DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at VueComponent.beforeDestroy (https://hcu8y.csb.app/node_modules/vant/lib/mixins/popup/index.js:87:24)
    at invokeWithErrorHandling (https://hcu8y.csb.app/node_modules/vue/dist/vue.common.dev.js:1859:57)
    at callHook (https://hcu8y.csb.app/node_modules/vue/dist/vue.common.dev.js:4210:7)

```

**Comment by chenjiahan** [comment]
重复 issue，在此 issue 中跟进 https://github.com/youzan/vant/issues/4760
