### ISSUE TITLE
vant升级到2.3.3报错

### ISSUE THREAD

**Issue by maomaoliangliang** [youzan/vant#5435]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater

**Comment by maomaoliangliang** [comment]
Module build failed (from ./node_modules/_eslint-loader@2.2.1@eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
    at OffsetStorage.setDesiredOffset (D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\rules\indent.js:335:45)
    at D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\rules\indent.js:1310:29
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\rules\indent.js:1304:34)
    at D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\rules\indent.js:1496:55
    at Array.forEach (<anonymous>)
    at Program:exit (D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\rules\indent.js:1496:26)
    at D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\util\safe-emitter.js:47:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\util\node-event-generator.js:303:14)
    at CodePathAnalyzer.leaveNode (D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\code-path-analysis\code-path-analyzer.js:630:23)
    at Traverser.leave [as _leave] (D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\linter.js:868:28)
    at Traverser._traverse (D:\WF\new-wx-app\wf-iot-living-h5\wf-iot-living-h5\iot_v2\node_modules\_eslint@4.19.1@eslint\lib\util\traverser.js:155:18)

 @ ./src/router/handleEnv/_import_development.js 125:11-127:25
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@3.10.1@webpack-dev-server/client?http://192.168.3.151:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by chenjiahan** [comment]
看报错和 Vant 没关系呢，建议排查下是不是其他问题

**Comment by maomaoliangliang** [comment]
好的，谢谢




| |
13631452939
|
|
邮箱：13631452939@163.com
|

Signature is customized by Netease Mail Master

在2019年12月31日 18:50，neverland 写道：

Closed #5435.
