### ISSUE TITLE
vue-server-renderer问题

### ISSUE THREAD

**Issue by JaweenDeng** [youzan/vant#6042]
Cannot read property 'children' of null
    at sortChildren (/data/java/git/gitee/ais-html/mm.ais.cn/node_modules/vant/lib/utils/vnodes.js:26:44)
    at VueComponent.bindRelation (/data/java/git/gitee/ais-html/mm.ais.cn/node_modules/vant/lib/mixins/relation.js:56:34)
    at Proxy.ChildrenMixin._vue.default.extend.computed._computed.<computed> (/data/java/git/gitee/ais-html/mm.ais.cn/node_modules/vant/lib/mixins/relation.js:34:12)

通过vue-server-renderer改造后的运行，报错

**Comment by fusyd** [comment]
同问，nuxt ssr同样的问题。

```
ERROR Cannot read property 'children' of null
at sortChildren (node_modules/_vant@2.6.0@vant/lib/utils/vnodes.js:26:44)
at a.bindRelation (node_modules/_vant@2.6.0@vant/lib/mixins/relation.js:56:34)
at a.ChildrenMixin._vue.default.extend.computed._computed.<computed> (node_modules/_vant@2.6.0@vant/lib/mixins/relation.js:34:12)
at a.index (node_modules/_vue@2.6.11@vue/dist/vue.runtime.common.prod.js:6:29698)
at a.shouldRender (node_modules/_vant@2.6.0@vant/lib/swipe-item/index.js:48:24)
at a.shouldRender (node_modules/_vue@2.6.11@vue/dist/vue.runtime.common.prod.js:6:29698)
at a.render (node_modules/_vant@2.6.0@vant/lib/swipe-item/index.js:74:14)
at a.t._render (node_modules/_vue@2.6.11@vue/dist/vue.runtime.common.prod.js:6:35273)
at node_modules/_vue-server-renderer@2.6.11@vue-server-renderer/build.prod.js:1:70665
at Yi (node_modules/_vue-server-renderer@2.6.11@vue-server-renderer/build.prod.js:1:67229)
```

**Comment by chenjiahan** [comment]
感谢反馈，已在 2.6.1 版本修复
