### ISSUE TITLE
[Bug Report] Vant库在本地无法运行

### ISSUE THREAD

**Issue by david2tdw** [youzan/vant#6366]
### 设备 / 浏览器
chrome

### Vant 版本
2.8.3

### Vue 版本
2.6.11

### 描述问题
你好， 我把最新的vant 库克隆到本地后，在运行以下命令后报错，请问有什么办法处理吗？ 还是我缺少了什么步骤？

thanks.
```
git clone https://github.com/youzan/vant.git
npm install
cd vant
npm run dev
```

错误：
E:\work_items\vant-dev -> origin\vant (dev -> origin) (vant@2.8.3)
$ npm run dev

> vant@2.8.3 dev E:\work_items\vant-dev\vant
> vant-cli dev

E:\work_items\vant-dev\vant\node_modules\fs-extra\lib\mkdirs\make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\work_items\vant-dev\vant\node_modules\fs-extra\lib\mkdirs\index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vant@2.8.3 dev: `vant-cli dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vant@2.8.3 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RS\AppData\Roaming\npm-cache\_logs\2020-05-25T05_48_16_038Z-debug.log

**Comment by david2tdw** [comment]
系统：
windows 7
npm@5.6.0
node@v8.11.2

**Comment by david2tdw** [comment]
已解决。
node版本过低导致出错。
