### ISSUE TITLE
[Bug Report] 新增 Popover 气泡弹出框会导致nuxt2.14.1版本编译失败

### ISSUE THREAD

**Issue by GongZuoHao** [youzan/vant#7616]
### 设备 / 浏览器
edge

### Vant 版本
2.11.0

### Vue 版本
2.6.11

### 重现链接
<a href="https://vant-contrib.gitee.io/vant/#/zh-CN/popover#jie-shao" target="_blank">https://vant-contrib.gitee.io/vant/#/zh-CN/popover#jie-shao</a>

### 描述问题
ERROR  Cannot use import statement outside a module

  (function (exports, require, module, __filename, __dirname) { import { popperGenerator, detectOverflow } from "./createPopper.js";
  ^^^^^^
  
  SyntaxError: Cannot use import statement outside a module
  at new Script (vm.js:88:7)
  at createScript (vm.js:263:10)
  at Object.runInThisContext (vm.js:311:10)
  at wrapSafe (internal/modules/cjs/loader.js:1041:15)
  at Module._compile (internal/modules/cjs/loader.js:1102:27)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
  at Module.load (internal/modules/cjs/loader.js:986:32)
  at Function.Module._load (internal/modules/cjs/loader.js:879:14)
  at Module.require (internal/modules/cjs/loader.js:1026:19)
  at require (internal/modules/cjs/helpers.js:72:18)

**Comment by want2012** [comment]
我也出现了同样的问题，请问最后如何解决呢？

**Comment by tangaoyu520hf** [comment]
I have the same problem, how to solve it in the end?
