### ISSUE TITLE
TypeError: Cannot read property 'width' of null

### ISSUE THREAD

**Issue by git-onepixel** [youzan/vant#7627]
在Android下大量报这个错误：

TypeError: Cannot read property 'width' of null
at a.minOffset (https://cdn.hellobike.com/npm/vant@2.6.3/lib/vant.min.js:7:141998)
at fn.get (https://cdn.hellobike.com/npm/vue@2.6.11/dist/vue.min.js:6:26768)
at fn.evaluate (https://cdn.hellobike.com/npm/vue@2.6.11/dist/vue.min.js:6:27918)
at a.minOffset (https://cdn.hellobike.com/npm/vue@2.6.11/dist/vue.min.js:6:29822)
at a.move (https://cdn.hellobike.com/npm/vant@2.6.3/lib/vant.min.js:7:143778)
at https://cdn.hellobike.com/npm/vant@2.6.3/lib/vant.min.js:7:144302

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
