### ISSUE TITLE
[Bug Report] Vant Cli 构建时RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lvreninfo** [youzan/vant#7737]
### 设备 / 浏览器
window64； node-v13.12.0

### Vant 版本
3.0.0-rc.3

### Vue 版本
3.0.4

### 重现链接
<a href="https://jsbin.com/kovoxen/edit?js" target="_blank">https://jsbin.com/kovoxen/edit?js</a>

### 描述问题
Vant Cli 构建时RangeError: Maximum call stack size exceeded

$ vant-cli dev
path.js:265
  normalize(path) {
           ^

RangeError: Maximum call stack size exceeded
    at Object.normalize (path.js:265:12)
    at Object.join (path.js:429:18)
    at findRootDir (D:\Desktop\ciopharma\zTest\node_modules\@vant\cli\lib\common\constant.js:11:38)
    at findRootDir (D:\Desktop\ciopharma\zTest\node_modules\@vant\cli\lib\common\constant.js:14:12)
    at findRootDir (D:\Desktop\ciopharma\zTest\node_modules\@vant\cli\lib\common\constant.js:14:12)
    at findRootDir (D:\Desktop\ciopharma\zTest\node_modules\@vant\cli\lib\common\constant.js:14:12)
    at findRootDir (D:\Desktop\ciopharma\zTest\node_modules\@vant\cli\lib\common\constant.js:14:12)
    at findRootDir (D:\Desktop\ciopharma\zTest\node_modules\@vant\cli\lib\common\constant.js:14:12)
    at findRootDir (D:\Desktop\ciopharma\zTest\node_modules\@vant\cli\lib\common\constant.js:14:12)
    at findRootDir (D:\Desktop\ciopharma\zTest\node_modules\@vant\cli\lib\common\constant.js:14:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chenjiahan** [comment]
已在 @vant/cli@3.1.6 版本修复
