### ISSUE TITLE
vite引入less文件报错

### ISSUE THREAD

**Issue by scutcl** [youzan/vant#7916]
import 'vant/lib/index.less'

 /WorkSpace/Web/lmfx/node_modules/vant/lib/index.less?v=297dd175
  1  |  @import "./style/base.less";
     |                              ^
  2  |  @import "./action-bar/index.less";
  3  |  @import "./badge/index.less";
      at less (D:\WorkSpace\Web\lmfx\node_modules\vite\dist\node\chunks\dep-ce37d572.js:28762:33)
      at compileCSS (D:\WorkSpace\Web\lmfx\node_modules\vite\dist\node\chunks\dep-ce37d572.js:28616:40)
      at async TransformContext.transform (D:\WorkSpace\Web\lmfx\node_modules\vite\dist\node\chunks\dep-ce37d572.js:28423:48)
      at async Object.transform (D:\WorkSpace\Web\lmfx\node_modules\vite\dist\node\chunks\dep-ce37d572.js:52953:30)
      at async transformRequest (D:\WorkSpace\Web\lmfx\node_modules\vite\dist\node\chunks\dep-ce37d572.js:59227:29)
      at async D:\WorkSpace\Web\lmfx\node_modules\vite\dist\node\chunks\dep-ce37d572.js:59313:32

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by webliving** [comment]
@chenjiahan  什么模块, 引用 css 文件, 不能自定义皮肤

**Comment by Wen006** [comment]
这个错解决了么，我用antd 的pro- component的时候也是 less 文件这种错误
```shell
  1  |  @import '~antd/es/style/themes/default.less';
     |  ^
  2  |  
```

**Comment by a15218378694** [comment]
> 这个错解决了么，我用antd 的pro- component的时候也是 less 文件这种错误
> 
> ```shell
>   1  |  @import '~antd/es/style/themes/default.less';
>      |  ^
>   2  |  
> ```

我也是, 请问解决了吗
