### ISSUE TITLE
[Bug Report] vite ssr下运行server提示Sticky.js文件 ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by laizp** [youzan/vant#8403]
### 设备 / 浏览器
Win10 / Chrome

### Vant 版本
3.0.10

### Vue 版本
3.0.5

### 重现链接
<a href="https://gitee.com/hill-lai/vite-ssr-vant-sticky-test" target="_blank">https://gitee.com/hill-lai/vite-ssr-vant-sticky-test</a>

### 描述问题
1. 使用vite构建ssr应用，运行server.js时提示：
  ```js
  E:\Programs\vite-ssr-vant-sticky-test\node_modules\vant\lib\sticky\Sticky.js:26
      container: Element,
                 ^
  
  ReferenceError: Element is not defined
  ```
  即Node环境下不存在Element类的问题

2. 在`App.vue`文件中只引入了Button和ActionSheet组件，但是编译后生成的`dist/server/entry-server.js`文件中直接引入了整个vant库：
  ```js
  var vant = require("vant");
  ```
  而没有进行tree-shaking，导致会直接引入Sticky组件相关的文件，不知是我写法有问题还是这是vite或vant的问题？

**Comment by chenjiahan** [comment]
这个是 Vant 的问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 3.0.11 版本修复

**Comment by laizp** [comment]
还有一个问题
```bash
E:\**\node_modules\vant\es\button\style\index.js:1
import '../../style/base.css';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.<anonymous> (E:\**\dist\server\entry-server.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```
