### ISSUE TITLE
使用<script>加载VANT，在代码里如何使用import {Button} from 'vant'方式编写

### ISSUE THREAD

**Issue by yunfei01cs** [youzan/vant#9152]
之前框架使用npm引入方式，现在需要修改成script引入，以达到多模块共享文件。
调整成<script>加载，也调整了webpack的externals及TS的shim.d，原有其它类似import {Button} from 'vant'的代码不想进行调整。

但构建时提示These dependencies were not found:
* vant/es/button in ****

**Comment by chenjiahan** [comment]
这种情况需要把 babel-plugin-import 去掉

**Comment by yunfei01cs** [comment]
构建出错：Module build failed: Error: Cannot find module 'babel-plugin-import'
at Function.resolveSync [as sync] (****\node_modules\resolve\lib\sync.js:89:15)
    at resolveStandardizedName (****\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
