### ISSUE TITLE
本地构建主题的问题

### ISSUE THREAD

**Issue by hualongdai** [youzan/vant#981]
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net/dfarLdko/1/ or similar.**

**What is the expected behavior?**

**Which versions of Vant and Vue, and which browser / OS are affected by this issue? Did this work in previous versions of Vant?**

1. 改完var.css
2. npm run build

提示 没有 fs-extra 我又装了，然后又报下面的错，我又装了postcss-easy-import 但是还是报错

报错log：
events.js:193
      throw er; // Unhandled 'error' event
      ^
Error: Cannot find module 'postcss-easy-import'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)

**Comment by hualongdai** [comment]
我觉得 你们 开发的另一个库 zent，主题定制就很好，新建一个custom.theme.js 就可

**Comment by hualongdai** [comment]
这个已经好了。thx




| |
代华龙
高级前端工程师
|
|
便利蜂
保密
邮箱：fedlance@163.com
北京
机会总是留给有准备的人
|

签名由 网易邮箱大师 定制

在2018年05月13日 18:20，beysong 写道：

生成样式文件之后，怎么用的 @hualongdai
