### ISSUE TITLE
[Bug Report] 最新版(3.3.2)版本报错

### ISSUE THREAD

**Issue by long-hai-yang** [youzan/vant#9963]
### 重现链接

https://github.com/long-hai-yang/vant-test.git

### Vant 版本

3.3.2

### 描述一下你遇到的问题。

安装最新版本vant(3.3.2)，启动服务报错
```
上午9:25:53 [vite] Internal server error: Failed to resolve import "D:/project/vite-test/node_modules/vant/lib/vant/es/number-keyboard/style" from "src\main.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/project/vite-test/src/main.ts
  24 |    Dialog
  25 |  } from "vant";
  26 |  import 'D:/project/vite-test/node_modules/vant/lib/vant/es/number-keyboard/style';
     |          ^
  27 |  import 'D:/project/vite-test/node_modules/vant/lib/vant/es/button/style';
  28 |  import 'D:/project/vite-test/node_modules/vant/lib/vant/es/toast/style';
      at formatError (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:42189:46)
      at TransformContext.error (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:42185:19)
      at normalizeUrl (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:67284:26)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async TransformContext.transform (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:67424:57)
      at async Object.transform (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:42396:30)
      at async doTransform (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:56801:29)
```
![image](https://user-images.githubusercontent.com/21288565/143969903-8fa31a15-9711-4f73-a1b7-d2afbbd511f4.png)

 将vant固定在3.3.1以及更低版本不报错 

### 重现步骤

安装最新版本vant(3.3.2)，启动服务报错
```
上午9:25:53 [vite] Internal server error: Failed to resolve import "D:/project/vite-test/node_modules/vant/lib/vant/es/number-keyboard/style" from "src\main.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/project/vite-test/src/main.ts
  24 |    Dialog
  25 |  } from "vant";
  26 |  import 'D:/project/vite-test/node_modules/vant/lib/vant/es/number-keyboard/style';
     |          ^
  27 |  import 'D:/project/vite-test/node_modules/vant/lib/vant/es/button/style';
  28 |  import 'D:/project/vite-test/node_modules/vant/lib/vant/es/toast/style';
      at formatError (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:42189:46)
      at TransformContext.error (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:42185:19)
      at normalizeUrl (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:67284:26)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async TransformContext.transform (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:67424:57)
      at async Object.transform (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:42396:30)
      at async doTransform (D:\project\vite-test\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:56801:29)
```
![image](https://user-images.githubusercontent.com/21288565/143969903-8fa31a15-9711-4f73-a1b7-d2afbbd511f4.png)

将vant固定在3.3.1以及更低版本不报错

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/9957
